config/routes.rb
require "api_constraints"

Rails.application.routes.draw do
  mount Knock::Engine => "/knock" # used for API authentification
  
  get 'sessions/new'

  root 'users#index'
  
  resources :users
  resources :apps
  
  get "apikeys" => "apikeys#show", as: :apikey

  get      'login'       =>   'sessions#new'
  post     'login'       =>   'sessions#create'
  delete   'logout'      =>   'sessions#destroy'

  # API END POINTS
  namespace :api, defaults: { format: :json } do
    scope module: :v1,
                  constraints: ApiConstraints.new(version: 1, default: true) do
      resources :thefts, :only => [:show, :index, :create, :update, :destroy] do
        resources :positions, only: [:index, :show]
        resources :tags, only: [:index, :show]
      end
      resources :creators, :only => [:show, :index]
      resources :tags, only: [:index, :show] do 
        resources :thefts, only: [:show, :index]
      end
      resources :positions, only: [:index, :show]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    has_many :apps, dependent: :destroy
    
    validates :email,
              :presence => {:message => "du måste ange epost"},
              uniqueness: true
              
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
                        :presence => {:message => "felaktig epost"}
    has_secure_password
    validates :password, presence: true, length: { minimum: 1 }
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include SessionsHelper
    before_action :require_login, only: [:show]
    before_action :get_user, only: [:show]
    before_action :correct_user, only: [:show]
    before_action :logged_in_user, only: [:show]


    def index
        
    end
    
    def show
        if @user.admin?
            @users = User.all
            @apps = App.all
        else
            @user = get_user
            @apps = @user.apps
        end
    end
    
    def new
       @user = User.new 
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            session[:userid] = @user.id
            redirect_to @user
        else
            render :action => "new"
        end
    end
    
    ## log in actions
    
    def login
        u = User.find_by_email(params[:email])
        if u && u.authenticate(params[:password])
            log_in u
            session[:userid] = u.id
            redirect_back_or u
        else
            flash[:notice] = "Wrong user info, try again"
            redirect_to root_path
        end
    end

    def logout
        session.delete(:userid)
        redirect_to root_path, :notice => "logged out"
    end

    private
    
    def user_params
       params.require(:user).permit(:email, :password, :password_confirmation)
    end

    def get_user
        @user = User.find(params[:id])
    end
    
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
  def current_app_user?(user)
    user == current_app_user
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to current_app_user unless current_app_user?(@user)
  end    
    
end

app/helpers/users_helper.rb
module UsersHelper

    def log_in(user)
        session[:userid] = user.id
    end

end

app/views/users/index.html.erb
<div class="row">
    <p>welcome. please <%= link_to "log in", login_path %></p>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <div id="error_messages">
        <h2>Error: </h2>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for @user do |f| %>
        <%= f.label :email %>
        <%= f.email_field :email %>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>        

    <div>
        <%= f.submit "Register", class: "button button-primary" %>
    </div>
    
<% end %>

app/views/users/show.html.erb
<div class="row">
    <div class="page-title twelwe columns">
        <% if @user.admin? %>
            <h2>all apps</h2>
        <% else %>
            <h2>your apps</h2>
        <% end %>
    </div>
</div>
<div class="row">
    <div class="new-app">
        <%= link_to "New App", new_app_path %>
    </div>
</div>
<div>
    <% if @user.admin %>
        <% if @users.any? %>
            <% @users.each do | u | %>
                <div>
                    <%= u.email %>
                </div>
                <% if u.apps.any? %>
                    <div>
                        <% u.apps.each do | a | %>
                            <div>
                                <%= a.name %> : 
                                <%= a.api_key %>
                            </div>
                            <div>
                                <%= link_to "delete", a, method: :delete, class: "button",
                                                          data: { confirm: "You sure?" } %>
                            </div>
                        <%end%>
                    </div>
                <% else %>
                    <div>
                        no apps
                    </div>                
                <% end %>
                <hr />
            <%end%>
        <% end %>
    <% else %>
        <% if @apps.any? %>
            <% @apps.each do |app| %>
                <div>
                    <b><%= app.name %></b>
                </div>
                <div>
                    <%= app.api_key %>
                </div>
                <div>
                    <%= link_to "delete", app, method: :delete, class: "button",
                                              data: { confirm: "You sure?" } %>
                </div>                
                <hr />
            <% end %>
        <% end %>
    <% end %>

</div>